# Generated by Django 5.2.1 on 2025-05-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='age_group',
            field=models.CharField(choices=[('baby', 'Baby (0-24m)'), ('toddler', 'Toddler (2-4y)'), ('kids', 'Kids (4-7y)'), ('big_kids', 'Big Kids (8-12y)')], default='kids', max_length=20),
        ),
    ]
